In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("500m.csv")

In [4]:
df = data.drop(columns='Pressao')

In [5]:

# 2. Renomeia as colunas para o padrão em inglês que o seu RocketPy estava esperando no erro anterior
motor_data = df.rename(columns={'Tempo': 'Time(s)', 'Empuxo': 'Thrust(N)'})
motor_data = motor_data.reset_index(drop=True)

In [6]:
motor_data = motor_data.reset_index(drop=True)
motor_data

    Time(s)     Thrust(N)
0    277280    164.454559
1    277308    306.350647
2    277336   2978.766357
3    277364  13289.026367
4    277393  16632.234375
..      ...           ...
71   279298   1425.623413
72   279326   1054.402588
73   279354    726.428589
74   279382    618.077942
75   279411    563.376648

[76 rows x 2 columns]

In [ ]:
motor_data['Time(s)'] = (motor_data['Time(s)'] - motor_data['Time(s)'].iloc[0]) / 1000
motor_data['Thrust(N)'] = (motor_data['Thrust(N)']/1000)

In [8]:
motor_data

    Time(s)   Thrust(N)
0     0.000    1.644546
1     0.028    3.063506
2     0.056   29.787664
3     0.084  132.890264
4     0.113  166.322344
..      ...         ...
71    2.018   14.256234
72    2.046   10.544026
73    2.074    7.264286
74    2.102    6.180779
75    2.131    5.633766

[76 rows x 2 columns]

In [9]:
motor_data.to_csv('teste_estatico_2_500.csv', index=False)