In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("motor_teste_estatico_1.csv")

In [3]:
df = data.drop(columns='Pressao')

In [4]:
inicio = df[df['Tempo'] == 165281].index[0]

In [5]:
fim = df[df['Tempo'] == 173851].index[0]

In [6]:
motor_data = df.loc[inicio:fim]

In [7]:
motor_data

       Tempo     Empuxo
5779  165281  -6.077922
5780  165307  36.000000
5781  165332  44.298702
5782  165357  65.454552
5783  165382  56.688313
...      ...        ...
6100  173747  15.311689
6101  173772  21.740261
6102  173800   5.025974
6103  173826  18.350651
6104  173851  12.506494

[326 rows x 2 columns]

In [8]:
motor_data['Tempo'] = (motor_data['Tempo'] - motor_data['Tempo'].iloc[0]) / 1000
motor_data['Empuxo'] = (motor_data['Empuxo']/1000)

In [9]:
# 2. Renomeia as colunas para o padrão em inglês que o seu RocketPy estava esperando no erro anterior
motor_data = motor_data.rename(columns={'Tempo': 'Time(s)', 'Empuxo': 'Thrust(N)'})

In [10]:
motor_data.to_csv('motor_data_pronto.csv', index=False)

      Time(s)  Thrust(N)
5779    0.000  -0.006078
5780    0.026   0.036000
5781    0.051   0.044299
5782    0.076   0.065455
5783    0.101   0.056688
...       ...        ...
6100    8.466   0.015312
6101    8.491   0.021740
6102    8.519   0.005026
6103    8.545   0.018351
6104    8.570   0.012506

[326 rows x 2 columns]

In [25]:
df.to_csv('motor_thrust_teste.csv', index=False)